services:
  web:
    image: nginx:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./volume/nginx/nginx.conf:/etc/nginx/nginx.conf
